package org.com.asapplication.greendao.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import org.com.asapplication.greendao.DayStep;
import org.com.asapplication.greendao.GreenDaoEntity;

import org.com.asapplication.greendao.dao.DayStepDao;
import org.com.asapplication.greendao.dao.GreenDaoEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dayStepDaoConfig;
    private final DaoConfig greenDaoEntityDaoConfig;

    private final DayStepDao dayStepDao;
    private final GreenDaoEntityDao greenDaoEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dayStepDaoConfig = daoConfigMap.get(DayStepDao.class).clone();
        dayStepDaoConfig.initIdentityScope(type);

        greenDaoEntityDaoConfig = daoConfigMap.get(GreenDaoEntityDao.class).clone();
        greenDaoEntityDaoConfig.initIdentityScope(type);

        dayStepDao = new DayStepDao(dayStepDaoConfig, this);
        greenDaoEntityDao = new GreenDaoEntityDao(greenDaoEntityDaoConfig, this);

        registerDao(DayStep.class, dayStepDao);
        registerDao(GreenDaoEntity.class, greenDaoEntityDao);
    }
    
    public void clear() {
        dayStepDaoConfig.clearIdentityScope();
        greenDaoEntityDaoConfig.clearIdentityScope();
    }

    public DayStepDao getDayStepDao() {
        return dayStepDao;
    }

    public GreenDaoEntityDao getGreenDaoEntityDao() {
        return greenDaoEntityDao;
    }

}
